swagger: '2.0'
info:
  title: Koor API
  description: Happy to code Koor API
  version: '1.0.0'
schemes:
  - http
securityDefinitions:
  Koor:
    type: apiKey
    name: X-Koor-Application-Id
    in: header
basePath: /
produces:
  - application/json
paths:
  /koor/classes/users:
    get:
      security:
        - Koor: []
      summary: Get User Data By Username
      description: |
          Happy to access The System
      parameters:
        - name: username
          in: query
          description: username
          required: true
          type: string
          format: string
      responses:
        200:
            description: Returns a user data
        401:
            description: Unauthorized
        400:
            description: Bad Request
        406:
            description: Not Acceptable
        500:
            description: Server Internal error
      tags:
        - Users

