swagger: '2.0'
info:
  title: FE API
  description: Happy to code User API
  version: '1.0.0'
# the domain of the service
# host: api.sonnguyen.ws
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /api/v1/users/login:
    post:
      summary: Login with your account
      description: |
          Happy to access The System
      parameters:
        - name: username
          in: formData
          description: username for login
          required: true
          type: string
          format: string
        - name: password
          in: formData
          description: password for login
          required: true
          type: string
          format: string
      responses:
        200:
            description: Returns a access token
        401:
            description: Unauthorized
        400:
            description: Bad Request
        406:
            description: Not Acceptable
        500:
            description: Server Internal error
      tags:
        - Users

